### ISSUE TITLE
rospy.rostime.Time.from_seconds() can produce wrong conversion

### ISSUE THREAD

**Issue by qing-kudan** [ros/genpy#146]
When generating the msg header stamp with the `Time.from_seconds()` the converted result can be wrong, the following is one example
```
from rospy.rostime import Time
from sensor_msgs.msg import Imu
timestamp_ns = 10117469579
imu_msg = Imu() 
imu_msg.header.stamp = Time.from_seconds(timestamp_ns / 1e9)
assert Time.to_nsec(imu_msg.header.stamp) == timestamp_ns, '{} vs. {}'.format(Time.to_nsec(imu_msg.header.stamp), timestamp_ns)
---
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: 10117469578 vs. 10117469579
```

**Comment by gbiggs** [comment]
This is caused by inherent errors in floating point numbers. For demonstration, you can do the same calculations that are being done by the `Time` type yourself and observe the intermediate values:

```
In [1]: timestamp_ns = 10117469579

In [2]: timestamp_s = timestamp_ns / 1e9

In [3]: timestamp_s
Out[3]: 10.117469579

In [4]: secs = int(timestamp_s)

In [5]: secs
Out[5]: 10

In [6]: nsecs = int((timestamp_s - secs) * 1000000000)

In [7]: nsecs
Out[7]: 117469578

In [8]: timestamp_s - secs
Out[8]: 0.11746957899999977
```

As you can see, the subtraction of the seconds portion of the floating point value leads to a rounding error in the nanoseconds portion. When converted to an integer, this value is truncated rather than rounded up, which results in one nanosecond being lost.
